#  mkdir -p sonar/sonar/conf
#  mkdir -p sonar/sonar/data
#  mkdir -p sonar/sonar/logs
#  mkdir -p sonar/sonar/extensions
#  mkdir -p sonar/sonar/postgres
#  chmod -R 777 sonar
#
version: "3.3"
services:
   db:
     image: postgres:11.3
     container_name: sonarqube-postgres
     volumes:
       - $PWD/sonar/postgres:/var/lib/postgresql/data
#     ports:
#        - "5432:5432" 
     environment:
       - POSTGRES_USER=sonar 
       - POSTGRES_PASSWORD=sonar
       - TZ=Asia/Taipei
  
   sonarqube:
     image: sonarqube:7.7-community
     container_name: sonarqube
     ports:
         - "9000:9000"
         - "9092:9092"
     volumes:
        - /etc/localtime:/etc/localtime:ro
#        - $PWD/sonar/conf:/opt/sonarqube/conf
        - $PWD/sonar/data:/opt/sonarqube/data:Z
        - $PWD/sonar/logs:/opt/sonarqube/logs:Z
        - $PWD/sonar/extensions:/opt/sonarqube/extensions:Z
        - $PWD/sonar.properties:/opt/sonarqube/conf/sonar.properties
     links:
        - db
     environment:
        - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/sonar
        - TZ=Asia/Taipei
     depends_on:
      - db
